### ISSUE TITLE
Tests are unclear

### ISSUE THREAD

**Issue by jottinger** [messai-engineering/Yuga#2]
I'd like to issue a PR to bring the project into more clear idiomatic usage.

1) Ramove the multiple build systems. It looks like Maven is canonical; gradle is nice, b ut the duplication is not good. Solution would be to choose one (Maven.)
2) Change the tests to not rely on the default (unnamed) package, and remove the reliance on filesystems (using the classpath instead). This also prepares for future enhancement by adding tests that can fail (i.e., "this should not be parseable.")
3) Run analysis over the code to eliminate unnecessary features that are not needed
4) Minor spelling fixes
5) Add a correct and valid license (MIT, as proclaimed in the project description)

**Comment by johnjoseph** [comment]
Thanks for the suggestions! Much appreciated :)
Fixed them in PR #1
